/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author Meu Computador
 */
public class FrmCadastroAmigo extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadastroAmigo
     */
    public FrmCadastroAmigo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelNome = new javax.swing.JLabel();
        JLabelTelefone = new javax.swing.JLabel();
        CadastrarAmigos = new javax.swing.JLabel();
        JTFTelefone = new javax.swing.JTextField();
        JTFNome = new javax.swing.JTextField();
        JBVoltar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        JBCadastrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Amigos");
        getContentPane().setLayout(null);

        JLabelNome.setText("Nome:");
        getContentPane().add(JLabelNome);
        JLabelNome.setBounds(40, 59, 36, 16);

        JLabelTelefone.setText("Telefone:");
        getContentPane().add(JLabelTelefone);
        JLabelTelefone.setBounds(40, 175, 48, 16);

        CadastrarAmigos.setText("Cadastrar Amigos");
        getContentPane().add(CadastrarAmigos);
        CadastrarAmigos.setBounds(204, 6, 107, 16);

        JTFTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(JTFTelefone);
        JTFTelefone.setBounds(40, 209, 255, 22);

        JTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNomeActionPerformed(evt);
            }
        });
        getContentPane().add(JTFNome);
        JTFNome.setBounds(40, 93, 255, 22);

        JBVoltar.setText("Voltar");
        getContentPane().add(JBVoltar);
        JBVoltar.setBounds(47, 279, 72, 23);

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBCancelar);
        JBCancelar.setBounds(209, 279, 76, 23);

        JBCadastrar.setText("Cadastrar");
        getContentPane().add(JBCadastrar);
        JBCadastrar.setBounds(377, 279, 80, 23);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 145, 525, 24);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 249, 525, 24);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 29, 525, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pessoa4.jpg"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 40, 170, 320);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pessoa1.jpg"))); // NOI18N
        jLabel2.setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-40, 20, 500, 360);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo2.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 880, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFTelefoneActionPerformed

    private void JTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNomeActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        // Libera todos os recurso da interface gráfica
        this.dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroAmigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadastrarAmigos;
    private javax.swing.JButton JBCadastrar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBVoltar;
    private javax.swing.JLabel JLabelNome;
    private javax.swing.JLabel JLabelTelefone;
    private javax.swing.JTextField JTFNome;
    private javax.swing.JTextField JTFTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
