/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author Meu Computador
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuOpções = new javax.swing.JMenu();
        JMenuItemCadastoAmigo = new javax.swing.JMenuItem();
        JMenuItemCadastroFerramenta = new javax.swing.JMenuItem();
        JMenuItemGerenciarEmprestimos = new javax.swing.JMenuItem();
        JMenuItemGerenciarAmigos = new javax.swing.JMenuItem();
        JMenuItemGerenciarFerramentas = new javax.swing.JMenuItem();
        JMenuItemSair = new javax.swing.JMenuItem();
        JMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        JMenuOpções.setText("Opções");
        JMenuOpções.setToolTipText("");

        JMenuItemCadastoAmigo.setText("Cadastrar Amigo");
        JMenuItemCadastoAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemCadastoAmigoActionPerformed(evt);
            }
        });
        JMenuOpções.add(JMenuItemCadastoAmigo);

        JMenuItemCadastroFerramenta.setText("Cadastrar Ferramenta");
        JMenuOpções.add(JMenuItemCadastroFerramenta);

        JMenuItemGerenciarEmprestimos.setText("Gerenciar Empréstimos");
        JMenuOpções.add(JMenuItemGerenciarEmprestimos);

        JMenuItemGerenciarAmigos.setText("Gerenciar Amigos");
        JMenuOpções.add(JMenuItemGerenciarAmigos);

        JMenuItemGerenciarFerramentas.setText("Gerenciar Ferramentas");
        JMenuOpções.add(JMenuItemGerenciarFerramentas);

        JMenuItemSair.setText("Sair");
        JMenuOpções.add(JMenuItemSair);

        jMenuBar1.add(JMenuOpções);

        JMenuSobre.setText("Sobre");
        jMenuBar1.add(JMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleParent(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuItemCadastoAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemCadastoAmigoActionPerformed
        // Instancia a Tela de Cadastro de Amigos
        FrmCadastroAmigo objeto = new FrmCadastroAmigo();
        objeto.setVisible(true);
    }//GEN-LAST:event_JMenuItemCadastoAmigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuItemCadastoAmigo;
    private javax.swing.JMenuItem JMenuItemCadastroFerramenta;
    private javax.swing.JMenuItem JMenuItemGerenciarAmigos;
    private javax.swing.JMenuItem JMenuItemGerenciarEmprestimos;
    private javax.swing.JMenuItem JMenuItemGerenciarFerramentas;
    private javax.swing.JMenuItem JMenuItemSair;
    private javax.swing.JMenu JMenuOpções;
    private javax.swing.JMenu JMenuSobre;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
