/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author Meu Computador
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuOpções = new javax.swing.JMenu();
        JMenuCadastoAmigo = new javax.swing.JMenuItem();
        JMenuCadastroFerramenta = new javax.swing.JMenuItem();
        JMenuGerenciarEmprestimos = new javax.swing.JMenuItem();
        JMenuGerenciarAmigos = new javax.swing.JMenuItem();
        JMenuGerenciarFerramentas = new javax.swing.JMenuItem();
        JMenuSair = new javax.swing.JMenuItem();
        JMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JMenuOpções.setText("Opções");

        JMenuCadastoAmigo.setText("Cadastrar Amigo");
        JMenuCadastoAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuCadastoAmigoActionPerformed(evt);
            }
        });
        JMenuOpções.add(JMenuCadastoAmigo);

        JMenuCadastroFerramenta.setText("Cadastrar Ferramenta");
        JMenuOpções.add(JMenuCadastroFerramenta);

        JMenuGerenciarEmprestimos.setText("Gerenciar Empréstimos");
        JMenuOpções.add(JMenuGerenciarEmprestimos);

        JMenuGerenciarAmigos.setText("Gerenciar Amigos");
        JMenuOpções.add(JMenuGerenciarAmigos);

        JMenuGerenciarFerramentas.setText("Gerenciar Ferramentas");
        JMenuOpções.add(JMenuGerenciarFerramentas);

        JMenuSair.setText("Sair");
        JMenuOpções.add(JMenuSair);

        jMenuBar1.add(JMenuOpções);

        JMenuSobre.setText("Sobre");
        jMenuBar1.add(JMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuCadastoAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuCadastoAmigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenuCadastoAmigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuCadastoAmigo;
    private javax.swing.JMenuItem JMenuCadastroFerramenta;
    private javax.swing.JMenuItem JMenuGerenciarAmigos;
    private javax.swing.JMenuItem JMenuGerenciarEmprestimos;
    private javax.swing.JMenuItem JMenuGerenciarFerramentas;
    private javax.swing.JMenu JMenuOpções;
    private javax.swing.JMenuItem JMenuSair;
    private javax.swing.JMenu JMenuSobre;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
