/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author Meu Computador
 */
public class FrmOpções extends javax.swing.JFrame {

    /**
     * Creates new form FrmOpções
     */
    public FrmOpções() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastrarFerramenta = new javax.swing.JButton();
        VerFerramentas = new javax.swing.JButton();
        VerAmigos = new javax.swing.JButton();
        CadastrarAmigo = new javax.swing.JButton();
        CadastrarEmprestimo = new javax.swing.JButton();
        Emprestimos = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        BackGround = new javax.swing.JPanel();
        Relatorio = new javax.swing.JButton();
        Relatorio1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        NomeApp = new javax.swing.JLabel();
        SubTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fast Ferramentas - Menu Inicial");
        setBackground(new java.awt.Color(255, 255, 204));
        setMinimumSize(new java.awt.Dimension(500, 420));
        getContentPane().setLayout(null);

        CadastrarFerramenta.setText("Cadastrar Ferramenta");
        CadastrarFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarFerramentaActionPerformed(evt);
            }
        });
        getContentPane().add(CadastrarFerramenta);
        CadastrarFerramenta.setBounds(70, 110, 152, 23);

        VerFerramentas.setText("Ver Ferramentas");
        VerFerramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerFerramentasActionPerformed(evt);
            }
        });
        getContentPane().add(VerFerramentas);
        VerFerramentas.setBounds(270, 110, 152, 23);

        VerAmigos.setText("Ver Amigos");
        VerAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerAmigosActionPerformed(evt);
            }
        });
        getContentPane().add(VerAmigos);
        VerAmigos.setBounds(270, 150, 152, 23);

        CadastrarAmigo.setText("Cadastrar Amigo");
        CadastrarAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarAmigoActionPerformed(evt);
            }
        });
        getContentPane().add(CadastrarAmigo);
        CadastrarAmigo.setBounds(70, 150, 152, 23);

        CadastrarEmprestimo.setText("Cadastrar Empréstimo");
        CadastrarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarEmprestimoActionPerformed(evt);
            }
        });
        getContentPane().add(CadastrarEmprestimo);
        CadastrarEmprestimo.setBounds(70, 190, 152, 23);

        Emprestimos.setText("Ver Empréstimos");
        Emprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmprestimosActionPerformed(evt);
            }
        });
        getContentPane().add(Emprestimos);
        Emprestimos.setBounds(270, 190, 152, 23);

        Voltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Voltar.setForeground(new java.awt.Color(0, 0, 255));
        Voltar.setText("Voltar");
        Voltar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(200, 290, 80, 30);

        BackGround.setBackground(new java.awt.Color(255, 255, 204));
        BackGround.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        BackGround.setLayout(null);

        Relatorio.setText("Relatório Empréstimos");
        Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioActionPerformed(evt);
            }
        });
        BackGround.add(Relatorio);
        Relatorio.setBounds(260, 160, 152, 23);

        Relatorio1.setText("Relatório Ferramentas");
        Relatorio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Relatorio1ActionPerformed(evt);
            }
        });
        BackGround.add(Relatorio1);
        Relatorio1.setBounds(60, 160, 152, 23);

        getContentPane().add(BackGround);
        BackGround.setBounds(10, 70, 460, 270);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(null);

        NomeApp.setBackground(new java.awt.Color(0, 0, 0));
        NomeApp.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        NomeApp.setText("Fast Ferramentas");
        jPanel1.add(NomeApp);
        NomeApp.setBounds(130, 0, 240, 30);

        SubTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SubTitulo.setText("Opções");
        jPanel1.add(SubTitulo);
        SubTitulo.setBounds(200, 20, 210, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 460, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarFerramentaActionPerformed
        // Torna a tela de ferramenta visível
        FrmCadastroFerramenta objeto = new FrmCadastroFerramenta();
        objeto.setVisible(true);
    }//GEN-LAST:event_CadastrarFerramentaActionPerformed

    private void VerFerramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerFerramentasActionPerformed
        // Torna a tela de gerenciamento de ferramenta visível
        FrmGerenciaFerramenta objeto = new FrmGerenciaFerramenta();
        objeto.setVisible(true);
    }//GEN-LAST:event_VerFerramentasActionPerformed

    private void CadastrarAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarAmigoActionPerformed
        // Torna a tela de amigo visível
        FrmCadastroAmigo objeto = new FrmCadastroAmigo();
        objeto.setVisible(true);
    }//GEN-LAST:event_CadastrarAmigoActionPerformed

    private void VerAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerAmigosActionPerformed
        // Torna a tela de gerenciamento de amigos visível
        FrmGerenciaAmigo objeto = new FrmGerenciaAmigo();
        objeto.setVisible(true);
    }//GEN-LAST:event_VerAmigosActionPerformed

    private void CadastrarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarEmprestimoActionPerformed
        // Torna a tela de empréstimo visível
        FrmCadastroEmprestimo objeto = new FrmCadastroEmprestimo();
        objeto.setVisible(true);
    }//GEN-LAST:event_CadastrarEmprestimoActionPerformed

    private void EmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmprestimosActionPerformed
        // Torna a tela de gerenciamento de empréstimos visível
        FrmGerenciaEmprestimo objeto = new FrmGerenciaEmprestimo();
        objeto.setVisible(true);
    }//GEN-LAST:event_EmprestimosActionPerformed

    private void RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioActionPerformed
        // Torna a tela de relatórios visível
        FrmRelatorioEmprestimo objeto = new FrmRelatorioEmprestimo();
        objeto.setVisible(true);
    }//GEN-LAST:event_RelatorioActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // Volta para o menu inicial
        (this).setVisible(false);
    }//GEN-LAST:event_VoltarActionPerformed

    private void Relatorio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Relatorio1ActionPerformed
        // Torna a tela de relatórios visível
        FrmRelatorioFerramentas objeto = new FrmRelatorioFerramentas();
        objeto.setVisible(true);
    }//GEN-LAST:event_Relatorio1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOpções.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOpções.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOpções.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOpções.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmOpções().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JButton CadastrarAmigo;
    private javax.swing.JButton CadastrarEmprestimo;
    private javax.swing.JButton CadastrarFerramenta;
    private javax.swing.JButton Emprestimos;
    private javax.swing.JLabel NomeApp;
    private javax.swing.JButton Relatorio;
    private javax.swing.JButton Relatorio1;
    private javax.swing.JLabel SubTitulo;
    private javax.swing.JButton VerAmigos;
    private javax.swing.JButton VerFerramentas;
    private javax.swing.JButton Voltar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
